### ISSUE TITLE
No module named arsenal.alphabet

### ISSUE THREAD

**Issue by gozdesahin** [se4u/neural_wfst#2]
Hi,

I have installed all dependencies stated in the repo, yet I get the following error:

from transducer.src.transducer import Transducer
  File "src/transducer.pyx", line 25, in init python.transducer.src.transducer
ImportError: No module named arsenal.alphabet

Any help would be appreciated.

**Comment by se4u** [comment]
Hi, `arsenal` was a repo that a labmate wrote

https://github.com/timvieira/arsenal

I will add it to `requirements` also.
